[params]
  goToTop = true
  giscusTheme = "preferred_color_scheme"
  disableComments = false

[outputs]
  home = ["html"]

[menus]
  [[menus.main]]
    name = "Home"
    pageRef = "/"
    weight = 10

  # [[menus.main]]
  #   name = "Projects"
  #   pageref = "/projects/"
  #   weight = 20
  #
  # [[menus.main]]
  #   name = "Guides"
  #   pageref = "/guides/"
  #   weight = 30
    
  [[menus.main]]
    name = "Reviews"
    pageRef = "/reviews/"
    weight = 40

  [[menus.main]]
    name = "Blog"
    pageRef = "/blog/"
    weight = 50

  [[menus.main]]
    name = "About"
    pageRef = "/about/"
    weight = 60
