baseurl = "/"
theme = "re-terminal"


[params]
  goToTop = true
  giscusTheme = "catppuccin_macchiato"
  disableComments = false
  
  readingTime = true

  Toc = true
  TocTitle = "Table of Contents"

  contentTypeName = "./content/about/"

  showLastUpdated = true

  favicon = "./static/favicon.ico"

[outputs]
  home = ["html"]

[menus]
  # [[menus.main]]
  #   name = "Projects"
  #   pageref = "/projects/"
  #   weight = 20

  # [[menus.main]]
  #   name = "Guides"
  #   pageref = "/guides/"
  #   weight = 30
    
  [[menus.main]]
    name = "Reviews"
    pageRef = "/reviews/"
    weight = 40

  [[menus.main]]
    name = "Blog"
    pageRef = "/blog/"
    weight = 50

  [[menus.main]]
    name = "About"
    pageRef = "/about"
    weight = 60


#[module]
#  [[module.imports]]
#    path = "github.com/mirus-ua/hugo-theme-re-terminal"
